ersaauth/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    #url(r'^login/$', views.login, name='login'),
    #url(r'^logout/$', views.logout, name='logout'),
    #url(r'^password_change/$', views.password_change, name='password_change'),
    #url(r'^password_change/done/$', views.password_change_done, name='password_change_done'),
    url(r'^password_reset/$', views.password_reset, name='password_reset'),
    url(r'^password_reset/sent/$', views.password_reset_link_sent, name='password_reset_link_sent'),
    url(r'^password_reset/confirm/(?P<token>.+)/$',views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^password_reset/complete/$', views.password_reset_complete, name='password_reset_complete'),
]

ersaauth/forms.py
from django import forms
from django.conf import settings

from django.core.exceptions import ValidationError

import re

reg_pwd_strength = getattr(settings,
                                      'REG_PWD_STRENGTH',
                                      '^(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)(?=.*[!@#\$%\^&\*]).{8,}')

STRENGTH_VALIDATOR = re.compile(reg_pwd_strength)

class SetPasswordForm(forms.Form):
    """
    A form that lets a user change set their password without entering the old
    password
    """
    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
        'weak_password': "The strength of password is weak.",
    }
    new_password1 = forms.CharField(label="New password",
                                    widget=forms.PasswordInput)
    new_password2 = forms.CharField(label="New password confirmation",
                                    widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(SetPasswordForm, self).__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )

            if not STRENGTH_VALIDATOR.match(password2):
                raise forms.ValidationError(
                    self.error_messages['weak_password'],
                    code='weak_password',
                )
        return password2

ersaauth/templates/ersa_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans%3A400%7CRaleway" type="text/css"/>
  <link rel="stylesheet" href="https://portal.ersa.edu.au/register.css">
  {% block extrastyle %}{% endblock %}
  <!-- <link rel="stylesheet" href="../css/style.css"> -->

  <!--[if lt IE 9]>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style>
    body {
      font-family: "Open Sans";
      font-size: 16px;
      background-color: #fff;
      background: transparent url("https://portal.ersa.edu.au/ersa_login_bg_md.png");
      min-height: 736px;
      background-size: cover;
      background-position: 50% 30%;
      background-repeat: no-repeat;
    }
    h1, h2, h3, h3, h5 {
      font-family: "Raleway";
    }
   .centerBox {
      width: 480px;
      margin: 80px auto;
      min-width: 400px;
      max-width: 90%;
  }
  </style>
</head>

<body>
      <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="https://portal.ersa.edu.au">
                    <img style="margin-top: 5px;" src="https://www.ersa.edu.au/wp-content/uploads/2015/01/ers-logo-ver1.png" alt="eRSA portal">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="http://www.ersa.edu.au">HOME</a></li>
                    <li><a href="https://www.ersa.edu.au/support/">SUPPORT</a></li>
                    <li><a href="http://support.ersa.edu.au/home/">USER GUIDES</a></li>
                    <li><a href="https://www.ersa.edu.au/support/system-maintenance/">MAINTENANCE</a></li>
                    <li><a href="https://www.ersa.edu.au/support/faq/">FAQ</a></li>
                    <li><a href="https://register.ersa.edu.au/">REGISTER</a></li>
                </ul>
            </div>
        </div>
    </nav>


  <div class="container" >

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="centerBox">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
    </div>
    <!-- END Content -->
    </div>

    {% block footer %}<div id="footer"></div>{% endblock %}

</body>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/js/bootstrap.min.js" ></script>
</html>

ersaauth/templates/ersa_password_reset_complete.html
{% extends "ersa_base.html" %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}

{% block content %}

<p>Your password has been set.  To verfiy, you can go to <a href="{{ login_url }}" target="_blank">FIM</a> and log in now.</p>

{% endblock %}

ersaauth/templates/ersa_password_reset_confirm.html
{% extends "ersa_base.html" %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}

{% if validlink %}

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form action="" method="post" onsubmit="return validateForm();">{% csrf_token %}
<div class="text-danger">
  {{ form.new_password1.errors }}
</div>
<div class="form-group">
  <label for="id_new_password1" class="col-xs-5 col-sm-5 col-md-5 col-lg-5 control-label">New password:</label>{{ form.new_password1 }}
</div>

<div class="text-danger">
  {{ form.new_password2.errors }}
</div>
<div class="form-group">
  <label for="id_new_password2" class="col-xs-5 col-sm-5 col-md-5 col-lg-5 control-label">Confirm password:</label>{{ form.new_password2 }}
</div>

<div class="form-group"><input type="submit" value="Change my password" /></div>
</form>

<div>
  <p>&nbsp;</p> <!-- Can be imporoved by define a section padding</-->
  <h4>Password has to meet strength test. The requirements are:</h4>
  <ul>
    <li>it has to be at least 8 characters long</li>
    <li>it has to contains lower and upper letters and number</li>
    <li>it has to contains at least one special character: <code>!@#$%^&*</code></li>
  </ul>
</div>

<script>
//Backend helper. Untill grow bigger, put here
var strength = /^(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)(?=.*[!@#\$%\^&\*]).{8,}/;
var password_boxes = ['id_new_password1','id_new_password2'];
function validateForm() {
  var passess = [];
  password_boxes.forEach(function(box) {
    element = document.getElementById(box);
    console.log(element.value);
    passess.push(element.value);
  });
  if (passess[0].trim() === '' || passess[1].trim() === '') {
    alert("All fieds need to be filled");
    return false;
  }
  if (passess[0] != passess[1]) {
    alert("Passwords do not match");
    return false;
  } else {
    console.log("Matched");

    if (strength.test(passess[1])) {
        console.log("Strength test passed");
        return true;
    } else {
        alert("Password is weak");
        return false;
    }
  }
}
</script>

{% else %}

<p>The password reset link was invalid.</p>
<p> Possible reasons could be:</p>
<ul>
  <li>Expired: every token has a defined valid life span.</li>
  <li>Token is not complete: make sure the link has all the characters shown in the email.</li>
</ul>

{% endif %}

{% endblock %}

ersaauth/templates/ersa_password_reset_email.html
{% autoescape off %}
You're receiving this email because you requested a password reset for your user account at {{ site_name }}.

Please go to the following page and choose a new password:
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' token=token %}
{% endblock %}
Please contact Helpdesk in case you've forgotten your username.


The {{ site_name }} team

{% endautoescape %}

ersaauth/templates/ersa_password_reset_form.html
{% extends "ersa_base.html" %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}

<p>To reset your password, enter your email address below, and we'll send you instructions for setting a new one.</p>

<form action="" method="post">{% csrf_token %}
<div class="text-danger">
  {{ form.email.errors }}
</div>
<p><label for="id_email">Email address:</label> {{ form.email }}
  <input type="submit" value="Reset my password" /></p>
</form>

{% endblock %}

ersaauth/templates/ersa_password_reset_link_sent.html
{% extends "ersa_base.html" %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}

<p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

<p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>

{% endblock %}